import { createContext, useContext, useState } from "react";

/* ─────────────────────────────────────────────
   Translation map — add keys here, use t.* everywhere
   ───────────────────────────────────────────── */
const translations = {
  /* ══════════ HEBREW (default) ══════════ */
  he: {
    nav: {
      profile: "פרופיל",
      home: "בית",
      community: "קהילה",
      support: "תמיכה",
      logout: "התנתקות",
    },
    dash: {
      member: "חבר/ה",
      org: "BogrotNet — מנהיגות שווה",
      overview: "סקירה",
      communityUpdates: "עדכוני קהילה",
      communityUpdatesBody:
        "חדשות, הכרזות ויוזמות ממנהיגות שווה לחברים רשומים.",
      myProfile: "הפרופיל שלי",
      myProfileBody:
        "נהל מידע אישי, הגדרות פרטיות, וכיצד הפרופיל שלך מופיע לחברים אחרים.",
      active: "פעיל",
      viewDetails: "הצג פרטים →",
      welcomeBack: "ברוך/ה הבא/ה,",
      suggestedMembers: "חברים שיכולים לעזור",
      suggestedMembersSub: "חברי קהילה עם ניסיון שאולי יוכלו לסייע לך.",
      viewAll: "הצג הכל",
      quickActions: "פעולות מהירות",
      goToCommunity: "לקהילה",
      goToSupport: "מצא עזרה",
      goToProfile: "הפרופיל שלי",
    },
    community: {
      title: "קהילה",
      subtitle: "פוסטים, בקשות וחגיגות מהקהילה שלך.",
      sharePrompt: "שתף/י משהו עם הקהילה…",
      attachFile: "צרף קובץ",
      post: "פרסם",
      posting: "מפרסם…",
      noPosts: "אין פוסטים עדיין. היה/י הראשון/ה לשתף משהו.",
      requestsReceived: "בקשות שהתקבלו",
      noRequests: "אין בקשות עדיין.",
      accept: "קבל",
      decline: "דחה",
      delete: "מחק",
      upcomingBirthdays: "ימי הולדת קרובים",
      noBirthdays: "אין ימי הולדת קרובים.",
      today: "היום",
      inDays: (n) => `בעוד ${n} יום${n > 1 ? "ות" : ""}`,
      accepted: "התקבל",
      declined: "נדחה",
      by: "על ידי",
      authorProfile: "פרופיל הכותב",
      close: "סגור",
      like: "אהבתי",
      liked: "אהבתי",
      comment: "תגובה",
      comments: (n) => `${n} תגובות`,
      repost: "שתף מחדש",
      reposted: "שותף",
      commentPlaceholder: "כתוב/י תגובה...",
      send: "שלח",
      repostedBy: "שותף על ידי",
      originalPost: "פוסט מקורי",
      noComments: "אין תגובות עדיין. היה/י הראשון/ה!",
      addThoughtsPlaceholder: "הוסף/י את דעתך...",
    },
    support: {
      title: "תמיכה",
      subtitle: "מצא/י חברי קהילה לפי שם, תחום עיסוק, או מיקום כדי לבקש עזרה.",
      memberName: "שם חבר/ה",
      namePlaceholder: "לדוגמה: שרה כהן",
      profession: "מקצוע",
      professionPlaceholder: "לדוגמה: רופא, עורך דין",
      city: "עיר",
      cityPlaceholder: "לדוגמה: תל אביב",
      selectCity: "כל הערים",
      professionCategories: "תחומי עיסוק",
      clearFilters: "נקה הכל",
      search: "חפש",
      searching: "מחפש…",
      searchEmpty: "חפש/י לפי שם, תחום, או עיר כדי למצוא חברים שיכולים לעזור.",
      noResults: "לא נמצאו חברים תואמים. נסה/י להרחיב את החיפוש.",
      suggestedTitle: "מומלצים עבורך",
      suggestedSub: "חברי קהילה שאולי יוכלו לעזור על בסיס המקצוע שלהם.",
      viewProfile: "הצג פרופיל",
      sendRequest: "שלח בקשה",
      sent: "נשלח",
      myRequests: "הבקשות שלי",
      memberProfile: "פרופיל חבר/ה",
      close: "סגור",
      requestSent: "הבקשה נשלחה",
      accepted: "התקבל",
      declined: "נדחה",
      pending: "ממתין",
      done: "הושלם",
      markDone: "סמן כהושלם",
      email: "אימייל",
      phone: "טלפון",
      bio: "ביוגרפיה",
      helpNote: "במה אתה/את צריך/ה עזרה?",
      helpNotePlaceholder: "תאר/י בקצרה מה אתה/את מחפש/ת...",
      requestNote: "הערה לבקשה",
      reviewTitle: "הבקשה הושלמה!",
      reviewSub: (name) => `האם תרצה/י לכתוב ביקורת עבור ${name}?`,
      reviewPlaceholder: "שתף/י את החוויה שלך עם חבר/ת הקהילה...",
      submitReview: "שלח ביקורת",
      skipReview: "דלג",
    },
    profile: {
      greeting: (name) => `היי, ${name}`,
      myProfile: "הפרופיל שלי",
      subtitle: "שמור/י על המידע שלך מעודכן כדי שהקהילה תכיר אותך.",
      personalInfo: "מידע אישי",
      firstName: "שם פרטי",
      lastName: "שם משפחה",
      phone: "טלפון",
      birthDate: "תאריך לידה",
      city: "עיר",
      professionJob: "מקצוע / עבודה",
      bio: "ביוגרפיה",
      emailAddress: "כתובת אימייל",
      currentEmail: "אימייל נוכחי",
      change: "שנה",
      saveChanges: "שמור שינויים",
      saving: "שומר…",
      saved: "נשמר",
      uploadPhoto: "העלה תמונה",
      photoHint: "JPG או PNG · מקס 5 מגה",
      firstNamePlaceholder: "ג'יין",
      lastNamePlaceholder: "סמית'",
      phonePlaceholder: "+972 55 000 0000",
      cityPlaceholder: "תל אביב",
      professionPlaceholder: "מהנדסת תוכנה",
      bioPlaceholder: "ספר/י לקהילה על עצמך…",
      changeEmail: "שנה אימייל",
      emailModalSub: "אשר/י את הסיסמה הנוכחית כדי להמשיך.",
      currentPassword: "סיסמה נוכחית",
      newEmail: "אימייל חדש",
      cancel: "ביטול",
      confirm: "אשר",
      errorGeneral: "משהו השתבש. נסה/י שוב.",
      myPosts: "הפוסטים שלי",
      noMyPosts: "עדיין לא פרסמת פוסטים. לך לקהילה ושתף/י משהו!",
    },
    network: {
      joinNetwork: "הצטרף לרשת",
      inNetwork:   "ברשת שלי",
      connections: (n) => `${n} חיבורים`,
      networkCount: "חיבורים",
    },
    lang: { switcher: "שפה", he: "עברית", en: "English", ar: "العربية" },
    common: {
      justNow:    "עכשיו",
      minutesAgo: (n) => `לפני ${n} דקות`,
      hoursAgo:   (n) => `לפני ${n} שעות`,
      daysAgo:    (n) => `לפני ${n} ימים`,
    },
  },

  /* ══════════ ENGLISH ══════════ */
  en: {
    nav: {
      profile: "Profile",
      home: "Home",
      community: "Community",
      support: "Support",
      logout: "Log Out",
    },
    dash: {
      member: "Member",
      org: "BogrotNet — Manhigut Shava",
      overview: "Overview",
      communityUpdates: "Community Updates",
      communityUpdatesBody:
        "News, announcements, and initiatives from BogrotNet posted here for registered members.",
      myProfile: "My Profile",
      myProfileBody:
        "Manage your personal information, privacy settings, and how your profile appears to other members.",
      active: "Active",
      viewDetails: "View details →",
      welcomeBack: "Welcome back,",
      suggestedMembers: "Members Who Can Help",
      suggestedMembersSub: "Community members with relevant expertise who may be able to assist you.",
      viewAll: "View All",
      quickActions: "Quick Actions",
      goToCommunity: "Community",
      goToSupport: "Find Help",
      goToProfile: "My Profile",
    },
    community: {
      title: "Community",
      subtitle: "Posts, requests, and celebrations from your community.",
      sharePrompt: "Share something with the community…",
      attachFile: "Attach file",
      post: "Post",
      posting: "Posting…",
      noPosts: "No posts yet. Be the first to share something.",
      requestsReceived: "Requests Received",
      noRequests: "No requests yet.",
      accept: "Accept",
      decline: "Decline",
      delete: "Delete",
      upcomingBirthdays: "Upcoming Birthdays",
      noBirthdays: "No upcoming birthdays.",
      today: "Today",
      inDays: (n) => `In ${n} day${n > 1 ? "s" : ""}`,
      accepted: "Accepted",
      declined: "Declined",
      by: "by",
      authorProfile: "Author Profile",
      close: "Close",
      like: "Like",
      liked: "Liked",
      comment: "Comment",
      comments: (n) => `${n} comment${n !== 1 ? "s" : ""}`,
      repost: "Repost",
      reposted: "Reposted",
      commentPlaceholder: "Write a comment...",
      send: "Send",
      repostedBy: "Reposted by",
      originalPost: "Original Post",
      noComments: "No comments yet. Be the first!",
      addThoughtsPlaceholder: "Add your thoughts...",
    },
    support: {
      title: "Support",
      subtitle: "Find community members by name, field, or location to request assistance.",
      memberName: "Member Name",
      namePlaceholder: "e.g. Sara Cohen",
      profession: "Profession",
      professionPlaceholder: "e.g. Doctor, Lawyer",
      city: "City",
      cityPlaceholder: "e.g. Tel Aviv",
      selectCity: "All Cities",
      professionCategories: "Profession Categories",
      clearFilters: "Clear All",
      search: "Search",
      searching: "Searching…",
      searchEmpty: "Search by name, field, or city to find members who can help.",
      noResults: "No matching members found. Try broadening your search.",
      suggestedTitle: "Suggested for You",
      suggestedSub: "Community members who may be able to help based on their profession.",
      viewProfile: "View Profile",
      sendRequest: "Send Request",
      sent: "Sent",
      myRequests: "My Requests",
      memberProfile: "Member Profile",
      close: "Close",
      requestSent: "Request Sent",
      accepted: "Accepted",
      declined: "Declined",
      pending: "Pending",
      done: "Done",
      markDone: "Mark as Done",
      email: "Email",
      phone: "Phone",
      bio: "Bio",
      helpNote: "What do you need help with?",
      helpNotePlaceholder: "Briefly describe what you're looking for...",
      requestNote: "Request Note",
      reviewTitle: "Request Completed!",
      reviewSub: (name) => `Would you like to write a review for ${name}?`,
      reviewPlaceholder: "Share your experience with this community member...",
      submitReview: "Submit Review",
      skipReview: "Skip",
    },
    profile: {
      greeting: (name) => `Hey, ${name}`,
      myProfile: "My Profile",
      subtitle: "Keep your info up to date so your community knows you.",
      personalInfo: "Personal Information",
      firstName: "First Name",
      lastName: "Last Name",
      phone: "Phone",
      birthDate: "Birth Date",
      city: "City",
      professionJob: "Profession / Job",
      bio: "Bio",
      emailAddress: "Email Address",
      currentEmail: "Current Email",
      change: "Change",
      saveChanges: "Save Changes",
      saving: "Saving…",
      saved: "Saved",
      uploadPhoto: "Upload Photo",
      photoHint: "JPG or PNG · max 5 MB",
      firstNamePlaceholder: "Jane",
      lastNamePlaceholder: "Smith",
      phonePlaceholder: "+1 555 000 0000",
      cityPlaceholder: "Tel Aviv",
      professionPlaceholder: "Software Engineer",
      bioPlaceholder: "Tell the community about yourself…",
      changeEmail: "Change Email",
      emailModalSub: "Confirm your current password to continue.",
      currentPassword: "Current Password",
      newEmail: "New Email",
      cancel: "Cancel",
      confirm: "Confirm",
      errorGeneral: "Something went wrong. Please try again.",
      myPosts: "My Posts",
      noMyPosts: "You haven't posted anything yet. Go to Community and share something!",
    },
    network: {
      joinNetwork: "Join Network",
      inNetwork:   "In Network",
      connections: (n) => `${n} connection${n !== 1 ? "s" : ""}`,
      networkCount: "Connections",
    },
    lang: { switcher: "Language", he: "עברית", en: "English", ar: "العربية" },
    common: {
      justNow:    "just now",
      minutesAgo: (n) => `${n}m ago`,
      hoursAgo:   (n) => `${n}h ago`,
      daysAgo:    (n) => `${n}d ago`,
    },
  },

  /* ══════════ ARABIC ══════════ */
  ar: {
    nav: {
      profile: "الملف الشخصي",
      home: "الرئيسية",
      community: "المجتمع",
      support: "الدعم",
      logout: "تسجيل الخروج",
    },
    dash: {
      member: "عضو",
      org: "BogrotNet — مانهيجوت شافا",
      overview: "نظرة عامة",
      communityUpdates: "تحديثات المجتمع",
      communityUpdatesBody:
        "أخبار وإعلانات ومبادرات من مانهيجوت شافا للأعضاء المسجلين.",
      myProfile: "ملفي الشخصي",
      myProfileBody:
        "إدارة معلوماتك الشخصية وإعدادات الخصوصية وكيفية ظهور ملفك للأعضاء الآخرين.",
      active: "نشط",
      viewDetails: "عرض التفاصيل →",
      welcomeBack: "مرحباً بعودتك،",
      suggestedMembers: "أعضاء يمكنهم المساعدة",
      suggestedMembersSub: "أعضاء المجتمع ذوو الخبرة الذين قد يتمكنون من مساعدتك.",
      viewAll: "عرض الكل",
      quickActions: "إجراءات سريعة",
      goToCommunity: "المجتمع",
      goToSupport: "اعثر على مساعدة",
      goToProfile: "ملفي الشخصي",
    },
    community: {
      title: "المجتمع",
      subtitle: "المنشورات والطلبات والاحتفالات من مجتمعك.",
      sharePrompt: "شارك شيئاً مع المجتمع…",
      attachFile: "إرفاق ملف",
      post: "نشر",
      posting: "جارٍ النشر…",
      noPosts: "لا توجد منشورات بعد. كن أول من يشارك شيئاً.",
      requestsReceived: "الطلبات المستلمة",
      noRequests: "لا توجد طلبات بعد.",
      accept: "قبول",
      decline: "رفض",
      delete: "حذف",
      upcomingBirthdays: "أعياد الميلاد القادمة",
      noBirthdays: "لا توجد أعياد ميلاد قادمة.",
      today: "اليوم",
      inDays: (n) => `بعد ${n} يوم`,
      accepted: "مقبول",
      declined: "مرفوض",
      by: "بواسطة",
      authorProfile: "ملف المؤلف",
      close: "إغلاق",
      like: "أعجبني",
      liked: "أعجبني",
      comment: "تعليق",
      comments: (n) => `${n} تعليقات`,
      repost: "إعادة نشر",
      reposted: "أُعيد نشره",
      commentPlaceholder: "اكتب تعليقاً...",
      send: "إرسال",
      repostedBy: "أُعيد نشره بواسطة",
      originalPost: "المنشور الأصلي",
      noComments: "لا توجد تعليقات بعد. كن الأول!",
      addThoughtsPlaceholder: "أضف أفكارك...",
    },
    support: {
      title: "الدعم",
      subtitle: "ابحث عن أعضاء المجتمع بالاسم أو المجال أو الموقع لطلب المساعدة.",
      memberName: "اسم العضو",
      namePlaceholder: "مثل: سارة كوهين",
      profession: "المهنة",
      professionPlaceholder: "مثل: طبيب، محامي",
      city: "المدينة",
      cityPlaceholder: "مثل: تل أبيب",
      selectCity: "جميع المدن",
      professionCategories: "فئات المهنة",
      clearFilters: "مسح الكل",
      search: "بحث",
      searching: "جارٍ البحث…",
      searchEmpty: "ابحث بالاسم أو المجال أو المدينة للعثور على أعضاء يمكنهم المساعدة.",
      noResults: "لم يتم العثور على أعضاء مطابقين. حاول توسيع نطاق البحث.",
      suggestedTitle: "مقترح لك",
      suggestedSub: "أعضاء المجتمع الذين قد يتمكنون من المساعدة بناءً على مهنتهم.",
      viewProfile: "عرض الملف الشخصي",
      sendRequest: "إرسال طلب",
      sent: "تم الإرسال",
      myRequests: "طلباتي",
      memberProfile: "الملف الشخصي للعضو",
      close: "إغلاق",
      requestSent: "تم إرسال الطلب",
      accepted: "مقبول",
      declined: "مرفوض",
      pending: "قيد الانتظار",
      done: "منتهٍ",
      markDone: "تحديد كمنتهٍ",
      email: "البريد الإلكتروني",
      phone: "الهاتف",
      bio: "نبذة",
      helpNote: "بماذا تحتاج المساعدة؟",
      helpNotePlaceholder: "اوصف بإيجاز ما تبحث عنه...",
      requestNote: "ملاحظة الطلب",
      reviewTitle: "اكتمل الطلب!",
      reviewSub: (name) => `هل تريد كتابة مراجعة لـ ${name}؟`,
      reviewPlaceholder: "شارك تجربتك مع هذا العضو...",
      submitReview: "إرسال المراجعة",
      skipReview: "تخطي",
    },
    profile: {
      greeting: (name) => `مرحباً، ${name}`,
      myProfile: "ملفي الشخصي",
      subtitle: "حافظ على تحديث معلوماتك حتى يتعرف عليك مجتمعك.",
      personalInfo: "المعلومات الشخصية",
      firstName: "الاسم الأول",
      lastName: "اسم العائلة",
      phone: "الهاتف",
      birthDate: "تاريخ الميلاد",
      city: "المدينة",
      professionJob: "المهنة / العمل",
      bio: "نبذة",
      emailAddress: "عنوان البريد الإلكتروني",
      currentEmail: "البريد الإلكتروني الحالي",
      change: "تغيير",
      saveChanges: "حفظ التغييرات",
      saving: "جارٍ الحفظ…",
      saved: "تم الحفظ",
      uploadPhoto: "تحميل صورة",
      photoHint: "JPG أو PNG · حجم أقصى 5 ميغابايت",
      firstNamePlaceholder: "جين",
      lastNamePlaceholder: "سميث",
      phonePlaceholder: "+970 55 000 0000",
      cityPlaceholder: "تل أبيب",
      professionPlaceholder: "مهندسة برمجيات",
      bioPlaceholder: "أخبر المجتمع عن نفسك…",
      changeEmail: "تغيير البريد الإلكتروني",
      emailModalSub: "أكد كلمة المرور الحالية للمتابعة.",
      currentPassword: "كلمة المرور الحالية",
      newEmail: "البريد الإلكتروني الجديد",
      cancel: "إلغاء",
      confirm: "تأكيد",
      errorGeneral: "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
      myPosts: "منشوراتي",
      noMyPosts: "لم تنشر أي شيء بعد. اذهب إلى المجتمع وشارك شيئاً!",
    },
    network: {
      joinNetwork: "انضم للشبكة",
      inNetwork:   "في شبكتي",
      connections: (n) => `${n} اتصالات`,
      networkCount: "الاتصالات",
    },
    lang: { switcher: "اللغة", he: "עברית", en: "English", ar: "العربية" },
    common: {
      justNow:    "الآن",
      minutesAgo: (n) => `منذ ${n} دقيقة`,
      hoursAgo:   (n) => `منذ ${n} ساعة`,
      daysAgo:    (n) => `منذ ${n} يوم`,
    },
  },
};

/* Languages that use RTL layout */
export const RTL_LANGS = ["he", "ar"];

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  /* Persist language selection; fall back to Hebrew on first visit */
  const [lang, setLangState] = useState(
    () => localStorage.getItem("lang") ?? "en"   // default English for new users
  );

  const setLang = (code) => {
    localStorage.setItem("lang", code);
    setLangState(code);
  };

  const t    = translations[lang] ?? translations.he;
  const isRTL = RTL_LANGS.includes(lang);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
