import { createContext, useContext, useState } from "react";

/* ─────────────────────────────────────────────
   Translation map — add keys here, use t.* everywhere
   ───────────────────────────────────────────── */
const translations = {
  /* ══════════ HEBREW (default) ══════════ */
  he: {
    nav: {
      profile: "פרופיל",
      home: "בית",
      community: "קהילה",
      support: "תמיכה",
      logout: "התנתקות",
    },
    dash: {
      member: "חבר/ה",
      org: "BogrotNet — מנהיגות שווה",
      overview: "סקירה",
      communityUpdates: "עדכוני קהילה",
      communityUpdatesBody:
        "חדשות, הכרזות ויוזמות ממנהיגות שווה לחברים רשומים.",
      myProfile: "הפרופיל שלי",
      myProfileBody:
        "נהל מידע אישי, הגדרות פרטיות, וכיצד הפרופיל שלך מופיע לחברים אחרים.",
      active: "פעיל",
      viewDetails: "הצג פרטים →",
      welcomeBack: "ברוך/ה הבא/ה,",
      suggestedMembers: "חברים שיכולים לעזור",
      suggestedMembersSub: "חברי קהילה עם ניסיון שאולי יוכלו לסייע לך.",
      viewAll: "הצג הכל",
      quickActions: "פעולות מהירות",
      goToCommunity: "לקהילה",
      goToSupport: "מצא עזרה",
      goToProfile: "הפרופיל שלי",
    },
    community: {
      title: "קהילה",
      subtitle: "פוסטים, בקשות וחגיגות מהקהילה שלך.",
      message: "הודעה",
      originalPostBy: "פוסט מקורי של",
      cancel: "ביטול",
      save: "שמור",
      confirmDelete: "להסיר את הפוסט הזה?",
      sharePrompt: "שתף/י משהו עם הקהילה…",
      attachFile: "צרף קובץ",
      post: "פרסם",
      posting: "מפרסם…",
      noPosts: "אין פוסטים עדיין.",
      noPostsSub: "היה/י הראשון/ה לשתף משהו עם הקהילה!",
      requestsReceived: "בקשות שהתקבלו",
      noRequests: "אין בקשות עדיין.",
      accept: "קבל",
      decline: "דחה",
      delete: "מחק",
      upcomingBirthdays: "ימי הולדת קרובים",
      noBirthdays: "אין ימי הולדת קרובים.",
      today: "היום",
      inDays: (n) => `בעוד ${n} יום${n > 1 ? "ות" : ""}`,
      accepted: "התקבל",
      declined: "נדחה",
      by: "על ידי",
      authorProfile: "פרופיל הכותב",
      close: "סגור",
      like: "אהבתי",
      liked: "אהבתי",
      comment: "תגובה",
      comments: (n) => `${n} תגובות`,
      repost: "שתף מחדש",
      reposted: "שותף",
      commentPlaceholder: "כתוב/י תגובה...",
      send: "שלח",
      repostedBy: "שותף על ידי",
      originalPost: "פוסט מקורי",
      noComments: "אין תגובות עדיין. היה/י הראשון/ה!",
      addThoughtsPlaceholder: "הוסף/י את דעתך...",
    },
    support: {
      title: "תמיכה",
      subtitle: "מצא/י חברי קהילה לפי שם, תחום עיסוק, או מיקום כדי לבקש עזרה.",
      memberName: "שם חבר/ה",
      namePlaceholder: "לדוגמה: שרה כהן",
      profession: "מקצוע",
      professionPlaceholder: "לדוגמה: רופא, עורך דין",
      city: "עיר",
      cityPlaceholder: "לדוגמה: תל אביב",
      selectCity: "כל הערים",
      professionCategories: "תחומי עיסוק",
      clearFilters: "נקה הכל",
      search: "חפש",
      searching: "מחפש…",
      searchEmpty: "חפש/י לפי שם, תחום, או עיר כדי למצוא חברים שיכולים לעזור.",
      noResults: "לא נמצאו חברים תואמים. נסה/י להרחיב את החיפוש.",
      suggestedTitle: "מומלצים עבורך",
      suggestedSub: "חברי קהילה שאולי יוכלו לעזור על בסיס המקצוע שלהם.",
      viewProfile: "הצג פרופיל",
      sendRequest: "שלח בקשה",
      sent: "נשלח",
      myRequests: "הבקשות שלי",
      memberProfile: "פרופיל חבר/ה",
      close: "סגור",
      requestSent: "הבקשה נשלחה",
      accepted: "התקבל",
      declined: "נדחה",
      pending: "ממתין",
      done: "הושלם",
      markDone: "סמן כהושלם",
      email: "אימייל",
      phone: "טלפון",
      bio: "ביוגרפיה",
      helpNote: "במה אתה/את צריך/ה עזרה?",
      helpNotePlaceholder: "תאר/י בקצרה מה אתה/את מחפש/ת...",
      requestNote: "הערה לבקשה",
      reviewTitle: "הבקשה הושלמה!",
      reviewSub: (name) => `האם תרצה/י לכתוב ביקורת עבור ${name}?`,
      reviewPlaceholder: "שתף/י את החוויה שלך עם חבר/ת הקהילה...",
      submitReview: "שלח ביקורת",
      skipReview: "דלג",
    },
    profile: {
      greeting: (name) => `היי, ${name}`,
      myProfile: "הפרופיל שלי",
      subtitle: "שמור/י על המידע שלך מעודכן כדי שהקהילה תכיר אותך.",
      personalInfo: "מידע אישי",
      firstName: "שם פרטי",
      lastName: "שם משפחה",
      phone: "טלפון",
      birthDate: "תאריך לידה",
      city: "עיר",
      professionJob: "מקצוע / עבודה",
      bio: "ביוגרפיה",
      emailAddress: "כתובת אימייל",
      currentEmail: "אימייל נוכחי",
      change: "שנה",
      saveChanges: "שמור שינויים",
      saving: "שומר…",
      saved: "נשמר",
      uploadPhoto: "העלה תמונה",
      photoHint: "JPG או PNG · מקס 5 מגה",
      firstNamePlaceholder: "ג'יין",
      lastNamePlaceholder: "סמית'",
      phonePlaceholder: "+972 55 000 0000",
      cityPlaceholder: "תל אביב",
      professionPlaceholder: "מהנדסת תוכנה",
      bioPlaceholder: "ספר/י לקהילה על עצמך…",
      changeEmail: "שנה אימייל",
      emailModalSub: "אשר/י את הסיסמה הנוכחית כדי להמשיך.",
      currentPassword: "סיסמה נוכחית",
      newEmail: "אימייל חדש",
      cancel: "ביטול",
      confirm: "אשר",
      errorGeneral: "משהו השתבש. נסה/י שוב.",
      myPosts: "הפוסטים שלי",
      posts: "פוסטים",
      noMyPosts: "עדיין לא פרסמת פוסטים. לך לקהילה ושתף/י משהו!",
      noPosts: "עוד לא פרסמה פוסטים.",
    },
    network: {
      joinNetwork: "הצטרף לרשת",
      inNetwork:   "ברשת שלי",
      connections: (n) => `${n} חיבורים`,
      networkCount: "חיבורים",
    },
    lang: { switcher: "שפה", he: "עברית", en: "English", ar: "العربية" },
    landing: {
      nav: { about: "אודות", features: "תכונות", how: "איך זה עובד", register: "הצטרפי עכשיו", signIn: "כניסה לחשבון", movementSite: "אתר התנועה" },
      hero: {
        badge: "פלטפורמה פנימית מאובטחת · בוגרות בלבד",
        headline1: "רשת נשים.",
        headline2: "כוח אמיתי.",
        subline: "רשת פרטית לבוגרות התנועה למנהיגות שווה. מצאי מומחיות, שלחי בקשות עזרה ובני קשרים מקצועיים עם הגנת פרטיות מלאה.",
        primaryCta: "הצטרפי עכשיו",
        secondaryCta: "כניסה לחשבון",
      },
      stats: [
        { target: "500+", label: "בוגרות" },
        { target: "10+", label: "שנות פעילות" },
        { target: "100%", label: "פרטי ומאובטח" },
      ],
      about: {
        label: "אודות הפלטפורמה",
        title: "הקשר שלא ידעת שאת צריכה",
        lead: "מנהיגות שווה היא תנועה בת עשור שמשתפת נשים מוכשרות ממגוון תחומים לקדם מנהיגות מגדרית שוויונית בישראל.",
        body: "הפלטפורמה הזו נבנתה כדי לחבר את הבוגרות — מקום אחד למצוא עזרה מקצועית, לשתף עדכונים, ולצמוח יחד.",
        tags: ["קהילה", "פרטיות", "מקצועיות"],
        memberCard: {
          role: "חברת קהילה",
          name: "מיכל לוי",
          profession: "עורכת דין · תל אביב",
          status: "פעילה",
          quote: "מצאתי שותפה עסקית ממחזור 3 תוך 24 שעות דרך הפלטפורמה. פשוט ממש.",
          badges: ["משפט", "יזמות", "ליטיגציה"],
          connections: "12 קשרים פעילים ברשת",
        },
      },
      featuresSection: {
        label: "תכונות הפלטפורמה",
        title: "בנוי לחיבורים אמיתיים",
        subtitle: "כל תכונה תוכננה סביב אמון, פרטיות ושיתוף פעולה משמעותי.",
      },
      features: [
        { title: "חיפוש חכם", desc: "חפשי לפי שם, מקצוע, עיר, או קטגוריה. תוצאות מיידיות עם פילטרים מדויקים." },
        { title: "בקשות עזרה", desc: "שלחי פנייה ישירה לבוגרת. פרטי קשר נחשפים רק לאחר אישור." },
        { title: "פיד קהילתי", desc: "שתפי עדכונים, הצלחות והזדמנויות. כל הקהילה בזרם אחד חי." },
        { title: "לוח מנהל", desc: "ניהול חברות, סטטיסטיקות, יומן פעילות מלא — הכול במקום אחד." },
        { title: "פרטיות מלאה", desc: "מידע קשר מוסתר כברירת מחדל. Firebase Auth, בקרת גישה מפורטת." },
        { title: "כל מכשיר", desc: "נייד, טאבלט, מחשב — חוויה חלקה בכל רזולוציה ובכל שפה." },
      ],
      howSection: {
        label: "איך זה עובד",
        title: "מההרשמה לחיבור — בדקות",
        subtitle: "תוכנן שכל בוגרת תשלים את ההצטרפות בקלות, ללא הדרכה.",
      },
      steps: [
        { n: "01", title: "הרשמה מהירה", desc: "מלאי את הפרטים שלך — שם, תחום, עיר, ביוגרפיה קצרה. לוקח 3 דקות." },
        { n: "02", title: "חפשי בוגרות", desc: "חפשי לפי מקצוע, מיקום, או שם. פילטרים מדויקים לתוצאות טובות יותר." },
        { n: "03", title: "שלחי בקשה", desc: "פני לבוגרת שיכולה לעזור. הפנייה שלך מגיעה אליה ישירות ובפרטיות." },
        { n: "04", title: "התחברי בביטחון", desc: "אחרי שהבוגרת אישרה — פרטי קשר משותפים. שיתוף הפעולה מתחיל." },
      ],
      testimonialsSection: { label: "מה הבוגרות אומרות", title: "קול הקהילה", quoteLabel: "חוות דעת" },
      testimonials: [
        { name: "דנה מ.", role: "מהנדסת · מחזור 7", text: "תוך שבוע מצאתי מנטורית שעזרה לי לקדם שינוי בחברה שלי. הפלטפורמה שינתה לי את הראש." },
        { name: "רונית ש.", role: "רופאה · מחזור 4", text: "סוף סוף מקום שמבין מה זה להיות אישה בכוח. הקהילה כאן חמה ומקצועית בו זמנית." },
        { name: "יעל ב.", role: "יזמית · מחזור 9", text: "שלושת השותפים שלי לעסק הגיעו מהפלטפורמה. לא צריך חיפוש אחר — הכל כאן." },
      ],
      cta: {
        title: "מוכנה להצטרף?",
        subtitle: "הצטרפי לרשת הבוגרות ותוכלי להתחבר עם מאות נשים מוכשרות שמקדמות ומקודמות.",
        primary: "הצטרפי לרשת",
        secondary: "יש לי כבר חשבון",
      },
      footer: {
        brand: "מנהיגות שווה · רשת הבוגרות",
        tagline: "רשת בוגרות לשיתוף מקצועי",
        movementSite: "אתר התנועה",
        copyright: "© 2026 · פלטפורמה פנימית מאובטחת",
      },
    },
    common: {
      justNow:    "עכשיו",
      minutesAgo: (n) => `לפני ${n} דקות`,
      hoursAgo:   (n) => `לפני ${n} שעות`,
      daysAgo:    (n) => `לפני ${n} ימים`,
      edited: "(נערך)",
      edit: "ערוך",
      cancel: "ביטול",
      save: "שמור",
      loading: "טוען…",
      mediaPost: "(פוסט מדיה)",
    },
  },

  /* ══════════ ENGLISH ══════════ */
  en: {
    nav: {
      profile: "Profile",
      home: "Home",
      community: "Community",
      support: "Support",
      logout: "Log Out",
    },
    dash: {
      member: "Member",
      org: "BogrotNet — Manhigut Shava",
      overview: "Overview",
      communityUpdates: "Community Updates",
      communityUpdatesBody:
        "News, announcements, and initiatives from BogrotNet posted here for registered members.",
      myProfile: "My Profile",
      myProfileBody:
        "Manage your personal information, privacy settings, and how your profile appears to other members.",
      active: "Active",
      viewDetails: "View details →",
      welcomeBack: "Welcome back,",
      suggestedMembers: "Members Who Can Help",
      suggestedMembersSub: "Community members with relevant expertise who may be able to assist you.",
      viewAll: "View All",
      quickActions: "Quick Actions",
      goToCommunity: "Community",
      goToSupport: "Find Help",
      goToProfile: "My Profile",
    },
    community: {
      title: "Community",
      subtitle: "Posts, requests, and celebrations from your community.",
      message: "Message",
      originalPostBy: "Original post by",
      cancel: "Cancel",
      save: "Save",
      confirmDelete: "Delete this post?",
      sharePrompt: "Share something with the community…",
      attachFile: "Attach file",
      post: "Post",
      posting: "Posting…",
      noPosts: "No posts yet",
      noPostsSub: "Be the first to share something with the community!",
      requestsReceived: "Requests Received",
      noRequests: "No requests yet.",
      accept: "Accept",
      decline: "Decline",
      delete: "Delete",
      upcomingBirthdays: "Upcoming Birthdays",
      noBirthdays: "No upcoming birthdays.",
      today: "Today",
      inDays: (n) => `In ${n} day${n > 1 ? "s" : ""}`,
      accepted: "Accepted",
      declined: "Declined",
      by: "by",
      authorProfile: "Author Profile",
      close: "Close",
      like: "Like",
      liked: "Liked",
      comment: "Comment",
      comments: (n) => `${n} comment${n !== 1 ? "s" : ""}`,
      repost: "Repost",
      reposted: "Reposted",
      commentPlaceholder: "Write a comment...",
      send: "Send",
      repostedBy: "Reposted by",
      originalPost: "Original Post",
      noComments: "No comments yet. Be the first!",
      addThoughtsPlaceholder: "Add your thoughts...",
    },
    support: {
      title: "Support",
      subtitle: "Find community members by name, field, or location to request assistance.",
      memberName: "Member Name",
      namePlaceholder: "e.g. Sara Cohen",
      profession: "Profession",
      professionPlaceholder: "e.g. Doctor, Lawyer",
      city: "City",
      cityPlaceholder: "e.g. Tel Aviv",
      selectCity: "All Cities",
      professionCategories: "Profession Categories",
      clearFilters: "Clear All",
      search: "Search",
      searching: "Searching…",
      searchEmpty: "Search by name, field, or city to find members who can help.",
      noResults: "No matching members found. Try broadening your search.",
      suggestedTitle: "Suggested for You",
      suggestedSub: "Community members who may be able to help based on their profession.",
      viewProfile: "View Profile",
      sendRequest: "Send Request",
      sent: "Sent",
      myRequests: "My Requests",
      memberProfile: "Member Profile",
      close: "Close",
      requestSent: "Request Sent",
      accepted: "Accepted",
      declined: "Declined",
      pending: "Pending",
      done: "Done",
      markDone: "Mark as Done",
      email: "Email",
      phone: "Phone",
      bio: "Bio",
      helpNote: "What do you need help with?",
      helpNotePlaceholder: "Briefly describe what you're looking for...",
      requestNote: "Request Note",
      reviewTitle: "Request Completed!",
      reviewSub: (name) => `Would you like to write a review for ${name}?`,
      reviewPlaceholder: "Share your experience with this community member...",
      submitReview: "Submit Review",
      skipReview: "Skip",
    },
    profile: {
      greeting: (name) => `Hey, ${name}`,
      myProfile: "My Profile",
      subtitle: "Keep your info up to date so your community knows you.",
      personalInfo: "Personal Information",
      firstName: "First Name",
      lastName: "Last Name",
      phone: "Phone",
      birthDate: "Birth Date",
      city: "City",
      professionJob: "Profession / Job",
      bio: "Bio",
      emailAddress: "Email Address",
      currentEmail: "Current Email",
      change: "Change",
      saveChanges: "Save Changes",
      saving: "Saving…",
      saved: "Saved",
      uploadPhoto: "Upload Photo",
      photoHint: "JPG or PNG · max 5 MB",
      firstNamePlaceholder: "Jane",
      lastNamePlaceholder: "Smith",
      phonePlaceholder: "+1 555 000 0000",
      cityPlaceholder: "Tel Aviv",
      professionPlaceholder: "Software Engineer",
      bioPlaceholder: "Tell the community about yourself…",
      changeEmail: "Change Email",
      emailModalSub: "Confirm your current password to continue.",
      currentPassword: "Current Password",
      newEmail: "New Email",
      cancel: "Cancel",
      confirm: "Confirm",
      errorGeneral: "Something went wrong. Please try again.",
      myPosts: "My Posts",
      posts: "Posts",
      noMyPosts: "You haven't posted anything yet. Go to Community and share something!",
      noPosts: "This member hasn't posted anything yet.",
    },
    network: {
      joinNetwork: "Join Network",
      inNetwork:   "In Network",
      connections: (n) => `${n} connection${n !== 1 ? "s" : ""}`,
      networkCount: "Connections",
    },
    lang: { switcher: "Language", he: "עברית", en: "English", ar: "العربية" },
    landing: {
      nav: { about: "About", features: "Features", how: "How it works", register: "Join now", signIn: "Sign in", movementSite: "Movement site" },
      hero: {
        badge: "Secure internal platform · alumnae only",
        headline1: "A women-led network.",
        headline2: "Real power.",
        subline: "A private network for BogrotNet alumnae. Find expertise, send help requests, and connect professionally with full privacy protection.",
        primaryCta: "Join now",
        secondaryCta: "Sign in",
      },
      stats: [
        { target: "500+", label: "Alumnae" },
        { target: "10+", label: "Years active" },
        { target: "100%", label: "Private & secure" },
      ],
      about: {
        label: "About the platform",
        title: "The connection you didn’t know you needed",
        lead: "BogrotNet is a decade-old movement bringing together talented women from diverse fields to advance gender-equal leadership in Israel.",
        body: "This platform was built to connect alumnae — one place to find professional support, share updates, and grow together.",
        tags: ["Community", "Privacy", "Professionalism"],
        memberCard: {
          role: "Community member",
          name: "Michal Levi",
          profession: "Lawyer · Tel Aviv",
          status: "Active",
          quote: "Within a week I found a business partner from cohort 3 through the platform. It was simply amazing.",
          badges: ["Law", "Entrepreneurship", "Litigation"],
          connections: "12 active network connections",
        },
      },
      featuresSection: {
        label: "Platform features",
        title: "Built for meaningful connections",
        subtitle: "Every feature is designed around trust, privacy, and meaningful collaboration.",
      },
      features: [
        { title: "Smart search", desc: "Search by name, profession, city, or category. Instant results with precise filters." },
        { title: "Help requests", desc: "Send a direct request to an alumna. Contact details only share after approval." },
        { title: "Community feed", desc: "Share updates, wins, and opportunities. Keep the whole community in one live stream." },
        { title: "Admin dashboard", desc: "Manage members, statistics, and activity logs — all in one place." },
        { title: "Full privacy", desc: "Contact details are hidden by default. Firebase Auth and fine-grained access control." },
        { title: "Any device", desc: "Mobile, tablet, desktop — smooth experience in every resolution and language." },
      ],
      howSection: {
        label: "How it works",
        title: "From sign-up to connection — in minutes",
        subtitle: "Designed so every alumna can complete onboarding easily, without training.",
      },
      steps: [
        { n: "01", title: "Quick sign-up", desc: "Fill in your details — name, field, city, short bio. It takes 3 minutes." },
        { n: "02", title: "Search alumnae", desc: "Search by profession, location, or name. Precise filters for better results." },
        { n: "03", title: "Send request", desc: "Reach out to an alumna who can help. Your message arrives privately and directly." },
        { n: "04", title: "Connect securely", desc: "After approval, contact details are shared. Collaboration begins." },
      ],
      testimonialsSection: { label: "What alumnae say", title: "Community voice", quoteLabel: "Testimonial" },
      testimonials: [
        { name: "Dana M.", role: "Engineer · Cohort 7", text: "Within a week I found a mentor who helped me advance change at my company. The platform changed my outlook." },
        { name: "Ronit S.", role: "Doctor · Cohort 4", text: "Finally a place that understands what it means to be a woman in power. The community here is warm and professional at once." },
        { name: "Yael B.", role: "Entrepreneur · Cohort 9", text: "My three business partners came from the platform. No need to search elsewhere — it’s all here." },
      ],
      cta: {
        title: "Ready to join?",
        subtitle: "Join the alumnae network and connect with hundreds of talented women who advance and support each other.",
        primary: "Join the network",
        secondary: "I already have an account",
      },
      footer: {
        brand: "BogrotNet — Alumnae Network",
        tagline: "A trusted network for alumnae",
        movementSite: "Movement site",
        copyright: "© 2026 · Secure internal platform",
      },
    },
    common: {
      justNow:    "just now",
      minutesAgo: (n) => `${n}m ago`,
      hoursAgo:   (n) => `${n}h ago`,
      daysAgo:    (n) => `${n}d ago`,
      edited: "(edited)",
      edit: "Edit",
      cancel: "Cancel",
      save: "Save",
      loading: "Loading…",
      mediaPost: "(media post)",
    },
  },

  /* ══════════ ARABIC ══════════ */
  ar: {
    nav: {
      profile: "الملف الشخصي",
      home: "الرئيسية",
      community: "المجتمع",
      support: "الدعم",
      logout: "تسجيل الخروج",
    },
    dash: {
      member: "عضو",
      org: "BogrotNet — مانهيجوت شافا",
      overview: "نظرة عامة",
      communityUpdates: "تحديثات المجتمع",
      communityUpdatesBody:
        "أخبار وإعلانات ومبادرات من مانهيجوت شافا للأعضاء المسجلين.",
      myProfile: "ملفي الشخصي",
      myProfileBody:
        "إدارة معلوماتك الشخصية وإعدادات الخصوصية وكيفية ظهور ملفك للأعضاء الآخرين.",
      active: "نشط",
      viewDetails: "عرض التفاصيل →",
      welcomeBack: "مرحباً بعودتك،",
      suggestedMembers: "أعضاء يمكنهم المساعدة",
      suggestedMembersSub: "أعضاء المجتمع ذوو الخبرة الذين قد يتمكنون من مساعدتك.",
      viewAll: "عرض الكل",
      quickActions: "إجراءات سريعة",
      goToCommunity: "المجتمع",
      goToSupport: "اعثر على مساعدة",
      goToProfile: "ملفي الشخصي",
    },
    community: {
      title: "المجتمع",
      subtitle: "المنشورات والطلبات والاحتفالات من مجتمعك.",
      message: "رسالة",
      originalPostBy: "المنشور الأصلي بواسطة",
      cancel: "إلغاء",
      save: "حفظ",
      confirmDelete: "حذف هذا المنشور؟",
      sharePrompt: "شارك شيئاً مع المجتمع…",
      attachFile: "إرفاق ملف",
      post: "نشر",
      posting: "جارٍ النشر…",
      noPosts: "لا توجد منشورات بعد",
      noPostsSub: "كن أول من يشارك شيئاً مع المجتمع!",
      requestsReceived: "الطلبات المستلمة",
      noRequests: "لا توجد طلبات بعد.",
      accept: "قبول",
      decline: "رفض",
      delete: "حذف",
      upcomingBirthdays: "أعياد الميلاد القادمة",
      noBirthdays: "لا توجد أعياد ميلاد قادمة.",
      today: "اليوم",
      inDays: (n) => `بعد ${n} يوم`,
      accepted: "مقبول",
      declined: "مرفوض",
      by: "بواسطة",
      authorProfile: "ملف المؤلف",
      close: "إغلاق",
      like: "أعجبني",
      liked: "أعجبني",
      comment: "تعليق",
      comments: (n) => `${n} تعليقات`,
      repost: "إعادة نشر",
      reposted: "أُعيد نشره",
      commentPlaceholder: "اكتب تعليقاً...",
      send: "إرسال",
      repostedBy: "أُعيد نشره بواسطة",
      originalPost: "المنشور الأصلي",
      noComments: "لا توجد تعليقات بعد. كن الأول!",
      addThoughtsPlaceholder: "أضف أفكارك...",
    },
    support: {
      title: "الدعم",
      subtitle: "ابحث عن أعضاء المجتمع بالاسم أو المجال أو الموقع لطلب المساعدة.",
      memberName: "اسم العضو",
      namePlaceholder: "مثل: سارة كوهين",
      profession: "المهنة",
      professionPlaceholder: "مثل: طبيب، محامي",
      city: "المدينة",
      cityPlaceholder: "مثل: تل أبيب",
      selectCity: "جميع المدن",
      professionCategories: "فئات المهنة",
      clearFilters: "مسح الكل",
      search: "بحث",
      searching: "جارٍ البحث…",
      searchEmpty: "ابحث بالاسم أو المجال أو المدينة للعثور على أعضاء يمكنهم المساعدة.",
      noResults: "لم يتم العثور على أعضاء مطابقين. حاول توسيع نطاق البحث.",
      suggestedTitle: "مقترح لك",
      suggestedSub: "أعضاء المجتمع الذين قد يتمكنون من المساعدة بناءً على مهنتهم.",
      viewProfile: "عرض الملف الشخصي",
      sendRequest: "إرسال طلب",
      sent: "تم الإرسال",
      myRequests: "طلباتي",
      memberProfile: "الملف الشخصي للعضو",
      close: "إغلاق",
      requestSent: "تم إرسال الطلب",
      accepted: "مقبول",
      declined: "مرفوض",
      pending: "قيد الانتظار",
      done: "منتهٍ",
      markDone: "تحديد كمنتهٍ",
      email: "البريد الإلكتروني",
      phone: "الهاتف",
      bio: "نبذة",
      helpNote: "بماذا تحتاج المساعدة؟",
      helpNotePlaceholder: "اوصف بإيجاز ما تبحث عنه...",
      requestNote: "ملاحظة الطلب",
      reviewTitle: "اكتمل الطلب!",
      reviewSub: (name) => `هل تريد كتابة مراجعة لـ ${name}؟`,
      reviewPlaceholder: "شارك تجربتك مع هذا العضو...",
      submitReview: "إرسال المراجعة",
      skipReview: "تخطي",
    },
    profile: {
      greeting: (name) => `مرحباً، ${name}`,
      myProfile: "ملفي الشخصي",
      subtitle: "حافظ على تحديث معلوماتك حتى يتعرف عليك مجتمعك.",
      personalInfo: "المعلومات الشخصية",
      firstName: "الاسم الأول",
      lastName: "اسم العائلة",
      phone: "الهاتف",
      birthDate: "تاريخ الميلاد",
      city: "المدينة",
      professionJob: "المهنة / العمل",
      bio: "نبذة",
      emailAddress: "عنوان البريد الإلكتروني",
      currentEmail: "البريد الإلكتروني الحالي",
      change: "تغيير",
      saveChanges: "حفظ التغييرات",
      saving: "جارٍ الحفظ…",
      saved: "تم الحفظ",
      uploadPhoto: "تحميل صورة",
      photoHint: "JPG أو PNG · حجم أقصى 5 ميغابايت",
      firstNamePlaceholder: "جين",
      lastNamePlaceholder: "سميث",
      phonePlaceholder: "+970 55 000 0000",
      cityPlaceholder: "تل أبيب",
      professionPlaceholder: "مهندسة برمجيات",
      bioPlaceholder: "أخبر المجتمع عن نفسك…",
      changeEmail: "تغيير البريد الإلكتروني",
      emailModalSub: "أكد كلمة المرور الحالية للمتابعة.",
      currentPassword: "كلمة المرور الحالية",
      newEmail: "البريد الإلكتروني الجديد",
      cancel: "إلغاء",
      confirm: "تأكيد",
      errorGeneral: "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
      myPosts: "منشوراتي",
      posts: "المنشورات",
      noMyPosts: "لم تنشر أي شيء بعد. اذهب إلى المجتمع وشارك شيئاً!",
      noPosts: "لم ينشر هذا العضو أي شيء بعد.",
    },
    network: {
      joinNetwork: "انضم للشبكة",
      inNetwork:   "في شبكتي",
      connections: (n) => `${n} اتصالات`,
      networkCount: "الاتصالات",
    },
    lang: { switcher: "اللغة", he: "עברית", en: "English", ar: "العربية" },
    landing: {
      nav: { about: "حول", features: "الميزات", how: "كيف يعمل", register: "انضمي الآن", signIn: "تسجيل الدخول", movementSite: "موقع الحركة" },
      hero: {
        badge: "منصة داخلية آمنة · للخرِيجات فقط",
        headline1: "شبكة نسائية.",
        headline2: "قوة حقيقية.",
        subline: "شبكة خاصة لخريجات BogrotNet. اعثرن على الخبرة، أرسلن طلبات مساعدة، وتواصلن مهنيًا مع حماية كاملة للخصوصية.",
        primaryCta: "انضمي الآن",
        secondaryCta: "تسجيل الدخول",
      },
      stats: [
        { target: "500+", label: "خرِيجات" },
        { target: "10+", label: "سنوات نشاط" },
        { target: "100%", label: "خاص وآمن" },
      ],
      about: {
        label: "عن المنصة",
        title: "الاتصال الذي لم تعرفي أنكِ بحاجة إليه",
        lead: "BogrotNet حركة عمرها عقد من الزمن تجمع نساء موهوبات من مجالات متنوعة لتعزيز القيادة المتساوية بين الجنسين في إسرائيل.",
        body: "تم بناء هذه المنصة لربط الخرِيجات — مكان واحد للعثور على دعم مهني، مشاركة التحديثات، والنمو معًا.",
        tags: ["المجتمع", "الخصوصية", "الاحترافية"],
        memberCard: {
          role: "عضوة المجتمع",
          name: "ميخال ليفي",
          profession: "محامية · تل أبيب",
          status: "نشطة",
          quote: "خلال أسبوع وجدت شريكة أعمال من المجموعة 3 عبر المنصة. كان ذلك رائعًا حقًا.",
          badges: ["قانون", "ريادة الأعمال", "تقاضي"],
          connections: "12 اتصالًا نشطًا بالشبكة",
        },
      },
      featuresSection: {
        label: "ميزات المنصة",
        title: "مصممة للروابط الحقيقية",
        subtitle: "كل ميزة مصممة حول الثقة والخصوصية والتعاون ذو المعنى.",
      },
      features: [
        { title: "بحث ذكي", desc: "ابحثي بالاسم أو المهنة أو المدينة أو الفئة. نتائج فورية مع مرشحات دقيقة." },
        { title: "طلبات مساعدة", desc: "أرسلي طلبًا مباشرًا لخريجة. يتم مشاركة البيانات بعد الموافقة فقط." },
        { title: "موجز المجتمع", desc: "شاركي التحديثات والنجاحات والفرص. احتفظي بالمجتمع كله في تدفق واحد مباشر." },
        { title: "لوحة تحكم", desc: "إدارة الأعضاء والإحصائيات وسجلات النشاط — كلها في مكان واحد." },
        { title: "خصوصية كاملة", desc: "يتم إخفاء تفاصيل الاتصال افتراضيًا. Firebase Auth وتحكم وصول مفصل." },
        { title: "أي جهاز", desc: "هاتف محمول، جهاز لوحي، كمبيوتر — تجربة سلسة في كل دقة وكل لغة." },
      ],
      howSection: {
        label: "كيف يعمل",
        title: "من التسجيل إلى الاتصال — في دقائق",
        subtitle: "مصممة حتى تكمل كل خريجة الانضمام بسهولة، دون تدريب.",
      },
      steps: [
        { n: "01", title: "تسجيل سريع", desc: "املأي تفاصيلك — الاسم والمجال والمدينة وسيرة قصيرة. يستغرق 3 دقائق." },
        { n: "02", title: "ابحثي عن الخريجات", desc: "ابحثي حسب المهنة أو الموقع أو الاسم. مرشحات دقيقة لنتائج أفضل." },
        { n: "03", title: "أرسلي طلبًا", desc: "تواصلي مع خريجة يمكنها المساعدة. يصل طلبك إليها مباشرة وبخصوصية." },
        { n: "04", title: "اتصال آمن", desc: "بعد الموافقة، تتم مشاركة بيانات الاتصال. يبدأ التعاون." },
      ],
      testimonialsSection: { label: "ماذا تقول الخريجات", title: "صوت المجتمع", quoteLabel: "شهادة" },
      testimonials: [
        { name: "دانا م.", role: "مهندسة · دفعة 7", text: "في غضون أسبوع وجدت مرشدة ساعدتني في دفع التغيير بشركتي. غيرت المنصة نظرتي." },
        { name: "رونيت ش.", role: "طبيبة · دفعة 4", text: "أخيرًا مكان يفهم ما يعني أن تكون امرأة في السلطة. المجتمع هنا دافئ ومحترف في آن معًا." },
        { name: "ياعيل ب.", role: "رائدة أعمال · دفعة 9", text: "جاء ثلاثة شركاء عملي من المنصة. لا حاجة للبحث في مكان آخر — كل شيء هنا." },
      ],
      cta: {
        title: "هل أنتِ جاهزة للانضمام؟",
        subtitle: "انضمّي إلى شبكة الخريجات ويمكنك التواصل مع مئات النساء الموهوبات اللاتي يدعمن ويقدمن بعضهن البعض.",
        primary: "انضمي إلى الشبكة",
        secondary: "لدي حساب بالفعل",
      },
      footer: {
        brand: "BogrotNet — شبكة الخريجات",
        tagline: "شبكة موثوقة للخريجات",
        movementSite: "موقع الحركة",
        copyright: "© 2026 · منصة داخلية آمنة",
      },
    },
    common: {
      justNow:    "الآن",
      minutesAgo: (n) => `منذ ${n} دقيقة`,
      hoursAgo:   (n) => `منذ ${n} ساعة`,
      daysAgo:    (n) => `منذ ${n} يوم`,
      edited: "(تم التعديل)",
      edit: "تعديل",
      cancel: "إلغاء",
      save: "حفظ",
      loading: "جارٍ التحميل…",
      mediaPost: "(منشور وسائط)",
    },
  },
};

/* Languages that use RTL layout */
export const RTL_LANGS = ["he", "ar"];

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  /* Persist language selection; fall back to Hebrew on first visit */
  const [lang, setLangState] = useState(
    () => localStorage.getItem("lang") ?? "en"   // default English for new users
  );

  const setLang = (code) => {
    localStorage.setItem("lang", code);
    setLangState(code);
  };

  const t    = translations[lang] ?? translations.he;
  const isRTL = RTL_LANGS.includes(lang);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
